"""remove_phone_from_students

Revision ID: 9de0e2d33632
Revises: c96404ca462e
Create Date: 2026-02-24 17:42:37.473711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de0e2d33632'
down_revision: Union[str, None] = 'c96404ca462e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
