"""add_access_groups

Revision ID: a0dac80a0bcd
Revises: 9de0e2d33632
Create Date: 2026-02-25 14:52:03.770467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0dac80a0bcd'
down_revision: Union[str, None] = '9de0e2d33632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('access_group_devices',
    sa.Column('access_group_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_group_id'], ['access_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('access_group_id', 'device_id')
    )
    op.create_table('access_group_students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['access_group_id'], ['access_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_group_id', 'student_id', name='uq_access_group_student')
    )
    op.create_index(op.f('ix_access_group_students_access_group_id'), 'access_group_students', ['access_group_id'], unique=False)
    op.create_index(op.f('ix_access_group_students_student_id'), 'access_group_students', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_group_students_student_id'), table_name='access_group_students')
    op.drop_index(op.f('ix_access_group_students_access_group_id'), table_name='access_group_students')
    op.drop_table('access_group_students')
    op.drop_table('access_group_devices')
    op.drop_table('access_groups')
    # ### end Alembic commands ###
