"""Centralized error codes for consistent API error responses."""


class ErrorCode:
    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"

    # Students
    STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND"
    STUDENT_DUPLICATE_EXTERNAL_ID = "STUDENT_DUPLICATE_EXTERNAL_ID"
    STUDENT_DUPLICATE_EMPLOYEE_NO = "STUDENT_DUPLICATE_EMPLOYEE_NO"
    INVALID_FACE_IMAGE = "INVALID_FACE_IMAGE"
    IMPORT_VALIDATION_ERROR = "IMPORT_VALIDATION_ERROR"

    # Attendance
    ATTENDANCE_NOT_FOUND = "ATTENDANCE_NOT_FOUND"
    INVALID_DATE_RANGE = "INVALID_DATE_RANGE"

    # Devices
    DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
    DEVICE_DUPLICATE_IP = "DEVICE_DUPLICATE_IP"
    DEVICE_OFFLINE = "DEVICE_OFFLINE"
    DEVICE_SYNC_FAILED = "DEVICE_SYNC_FAILED"

    # Webhooks
    WEBHOOK_NOT_FOUND = "WEBHOOK_NOT_FOUND"
    WEBHOOK_DELIVERY_FAILED = "WEBHOOK_DELIVERY_FAILED"
    INVALID_WEBHOOK_URL = "INVALID_WEBHOOK_URL"
    INVALID_WEBHOOK_EVENT = "INVALID_WEBHOOK_EVENT"

    # General
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
